#GET ALL ARTICLES
GET http://localhost:8080/articles?page=2

###
#GET ONE ARTICLE
GET http://localhost:8080/articles/1

###
#ADD A ARTICLE
POST http://localhost:8080/articles
Content-Type: application/json

{
    "title": "XYZ",
    "subtitle": "tata",
    "content": "Ranaghat Siliguri"
}

###
#SEARCH IMPLEMENTATION
GET http://localhost:8080/articles/search?q=ps4